### ISSUE TITLE
Use TopSolid Automating DLLs

### ISSUE THREAD

**Issue by gabrielandreussi** [ENAC-CNPA/Speckle.TopSolid#9]
Hello guys, I would like to ask: Why you don't use TopSolid Automating DLLs?
They are freely redistributable and are located at the TopSolid folder
"topsolid_folder\bin\TopSolid.Cam.NC.Kernel.Automating.dll"
All the dlls ended with .Automating were made to ease the access to TopSolid data and to make automations
It will make your work faster and more easy to develop!
Following their guide:

[TopSolid'Design Automation Guide.pdf](https://github.com/ENAC-CNPA/Speckle.TopSolid/files/8288816/TopSolid.Design.Automation.Guide.pdf)

**Comment by Choochoote** [comment]
Hi Gabriel,
Automating is based on WCF. Using Automation, you can replace a physical TopSolid user. 
TopSolid Core functionalities cannot be used with Automation,so I'm afraid it's not suitable here, making an AddIn is mandatory.

FYI there are several Automation:
=> kernel for basics
=> cam for FAO / machining
=> design for assemblies
=> wire for wire technlogies...
